export interface ProblemDetails {
  status?: number;
  title?: string;
  detail?: string;
  instance?: string;
  errors?: Record<string, string[]>;
}

export class ApiError extends Error {
  constructor(
    public readonly status: number,
    public readonly problem: ProblemDetails,
  ) {
    super(problem.title ?? `HTTP ${status}`);
    this.name = 'ApiError';
  }
}

// Paths generated by Orval already contain the full route from the OpenAPI spec
// (including any /api prefix); set VITE_API_URL only when the API runs on a
// different origin than the dev proxy / nginx.
const baseUrl: string = import.meta.env.VITE_API_URL ?? '';

// Used directly by feature code and as the Orval mutator (orval.config.ts).
export async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${baseUrl}${path}`, {
    headers: { 'Content-Type': 'application/json', ...init?.headers },
    ...init,
  });

  if (!response.ok) {
    const problem: ProblemDetails = await response
      .json()
      .catch(() => ({ title: response.statusText }));
    throw new ApiError(response.status, problem);
  }

  if (response.status === 204) {
    return undefined as T;
  }

  return (await response.json()) as T;
}
