sonar.projectKey={{solution-name-lower}}-web
sonar.projectName={{SolutionName}} Web
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=src/test/**,**/*.test.ts,**/*.test.tsx

sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.test.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
